### PR TITLE
[JENKINS-64188] Replace Netty with OkHttp

### PR DESCRIPTION
**Pull request by mezpahlan**
Mostly an internal plumbing job. Remove the Netty Http engine and favour OkHttp. It rocks! 

Also re-enable the ignored test for large file uploads.

### CODE REVIEW

**Comment by mezpahlan** [comment]
Looks good to me?

**Comment by thewolfwillcome** [comment]
This breaks. It seems its missing a dependency.
On jenkins LTS 2.249.3 with jre1.8.0_261 following error occurs:

java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt)
	at okhttp3.HttpUrl.get(HttpUrl.kt)
	at io.jenkins.plugins.appcenter.api.AppCenterServiceFactory.createAppCenterService(AppCenterServiceFactory.java:48)
	at io.jenkins.plugins.appcenter.task.internal.CreateUploadResourceTask.createUploadResourceForApp(CreateUploadResourceTask.java:55)
	at io.jenkins.plugins.appcenter.task.internal.CreateUploadResourceTask.execute(CreateUploadResourceTask.java:40)

**Comment by mezpahlan** [comment]
Hmm..... thanks @thewolfwillcome . Looking at that stacktrace I haven't changed that part of the code apart from upgrading the underlying library that provides `HttpUrl`. I'll do some research as to why this might be the case. 

In the mean time can you post your config for the job run please. Obviously redact anything sensitive.

For some background this changeset was supposed to help with uploading very large files over 250MB and _shouldn't_ have touched anything to do with normal uploads which your stacktrace suggests.

**Comment by mezpahlan** [comment]
Possibly this? https://github.com/square/okhttp/issues/5299

**Comment by mezpahlan** [comment]
OK that's very strange I've tried this via my usual testing method of `mvn hpi:run` which builds the source and fires up a Jenkins instance and loads the plugin so that I can test (that's pretty standard for Jenkins plugins I'm not doing anything custom there). And I tried a freestyle and a pipeline job which were successful. Even one on a different node than master. 

So I'm stumped at the moment. It could very well be the issue above but given that it works for me locally and the tests pass on the CI (and locally too) I'm not sure how to begin troubleshooting this :(. I'll have a think.

**Comment by mezpahlan** [comment]
#59 as an attempt to fix. Please continue discussion there.

**Comment by gabialex27** [comment]
Hi guys, I am using the latest version (0.10.1) of the Jenkins AppCenter plugin but the upload of the builds seems it has stopped to work - I receive the following error: io.jenkins.plugins.appcenter.AppCenterException: Create upload resource for app unsuccessful: HTTP 410 Gone: {"code":"gone","message":"This API is deprecated. Please use the latest version of the App Center CLI: https://github.com/microsoft/appcenter-cli, or if you need a custom script please use the CLI as the basis for your implementation. (Support ID: ea342f61-fecf-4da8-b9f6-f6870fb664ec)"}.

**Comment by mezpahlan** [comment]
Hi @gabialex27 this is being tracked here https://issues.jenkins.io/browse/JENKINS-64388. Please can you move any discussion there.

For others the issue is **not** related to this PR.

**Comment by gabialex27** [comment]
Yes, sure, thanks for the link and for the quick answer 👍

**Pull request merged**
