### PR TITLE
[JENKINS-59312] Enable variable in OwnerName, AppName and DistributionGroup configuration

### PR DESCRIPTION
**Pull request by Balthov60**

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @Balthov60 thanks for this PR. I want to try and find a way to merge #20 first but am having a few issues with getting that to work. Given that this is relatively small I am going to give myself until Friday to solve the other issues and then look again at this PR. Hope that's OK.

In the meantime I would start by asking if there are any tests that you can add to this.

**Comment by mezpahlan** [comment]
I've merged #20 now so am ready to have a look at this PR again. Thank you for your patience.

**Comment by Balthov60** [comment]
Great Thanks ! And I will try to add some tests.

**Comment by mezpahlan** [comment]
I've done the tests and merged this now. Thanks for starting this.

**Comment by Balthov60** [comment]
Thanks !

**Pull request merged**
