### PR TITLE
[JENKINS-58490] Support symbol file upload

### PR DESCRIPTION
**Pull request by Kilomoana83**
* [JENKINS-58490] added support for symbol file upload

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @Kilomoana83  apologies for the slow reply. I've been away and am only just catching up on these PRs. I've not forgot about this and will find some time this week to look at this again.

**Comment by Kilomoana83** [comment]
Hey Mez,

no problem, thanks for letting me know.

**Comment by Kilomoana83** [comment]
Hey Mez,

any update on this one? You want me to fix the conflicts first? My plan was to wait for your first comments before I touch it again.

**Comment by mezpahlan** [comment]
Hi @Kilomoana83 I want to merge in a few other changes first however they'll break your changes here. So what I'll do is merge my changes in first and then update this branch and start a review at that stage. If there are small comments I'll see if I can resolve them myself. If it there are any large comments I'll get back to you and we can discuss.

So in other words, hold off for now I'll get back to you soon. Thanks for starting this :)

**Comment by Kilomoana83** [comment]
Hey ok. Thanks for the effort so far! Really appreciated.

**Comment by mezpahlan** [comment]
Just to update you I am in a position to look at this now. I did try updating this branch but I think I need to sit down and understand the symbol file upload process a bit better first. I will get back to you with comments.

**Comment by mezpahlan** [comment]
The symbols upload process seems to mirror the file upload process in that you create a _bucket_ which you then upload the resource to. My current thoughts are that we should detect whether we have symbols to upload and create both _buckets_ at the same time in `CreateUploadResourceTask` then upload both of these in `CommitUploadResourceTask`.

I'm sure the way you've implemented it would work but I would rather not create the two abstract classes in the way you have. I'm quite keen to implement as much behaviour in these classes via composition instead of inheritance.

I think the changes I've made to the `master` branch will help with this but briefly this is how I would proceed.

1. Revert the changes to the abstract classes created here and remove the two extended classes.
1. Rename `CheckFilesTask` to `PrerequisiteTask` which will check the files exist a determine the symbol upload format (by the way, as a minimum we should aim to support both Android and IOS).
1. Return a new `UploadRequest` from `PrerequisiteTask` using the new `Builder` method available in `master` (there is already an example of how to do this in `master`). This will allow us to provide enough information to downstream tasks.
1. Revert the changes to `UploadTask`. The only purpose of this task is to compose other internal tasks. With these changes it's doing a lot more.

Now, I did try and update your branch with the changes from `master` but I fear it has moved on a bit too far. What I'll do is make a separate branch that I will share with you when I have made some progress and perhaps we can add back in your changes.

Fundamentally your approach is the correct one. I just want to make sure it is something I'm comfortable with maintaining long term so would like to shuffle some classes around in order to do that. Hope that helps :+1:

**Comment by carllindberg** [comment]
This is the PR I am waiting on before we switch to AppCenter -- so thanks to all involved in pushing this through :-)

**Comment by Kilomoana83** [comment]
Hey @mezpahlan,

sorry, I was on vacation. Will take a look at your PR today. Can I close this one already?

**Comment by mezpahlan** [comment]
Hi @Kilomoana83 I still need to do some work on that other PR if you are taking a look at it, but it is heading in the right direction.

**Comment by mezpahlan** [comment]
@Kilomoana83 I've tagged you in #37 could you cast your eye over that and (if you have the time) give it a go?

In the mean time I'll close this and we can pick up the conversation in the other PR. Many thanks again for starting the ball rolling.

**Pull request closed without merging**
