### PR TITLE
[JENKINS-58915] Raise connect timeout

### PR DESCRIPTION
**Pull request by ShurikuS57**
Upload app is fail:

> Creating an upload resource.
Upload resource successful.
Uploading app to resource.
Upload app unsuccessful.
java.net.SocketTimeoutException: timeout
io.jenkins.plugins.appcenter.AppCenterException: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
Build step 'Upload app to AppCenter' changed build result to FAILURE
Finished: FAILURE

Need rise connect timeout.

### CODE REVIEW

**Comment by mezpahlan** [comment]
Hi @ShurikuS57, thanks for the submission. Could you take a look at the Contributing section of the README and follow the steps to create a ticket please. We require a ticket in Jira first.

As for the actual change it looks sensible enough so am reasonably happy with it. I want to double check best practice with setting the timeout values first but in principle have no strong objection to increasing it.

**Comment by mezpahlan** [comment]
As discussed in the [bug report](https://issues.jenkins-ci.org/browse/JENKINS-58915) I've removed the other two timeout overrides. We're left with a 60 second connection timeout and a 60 second write timeout per packet. Hopefully that resolves your issue as I don't believe you had an issue with read timeouts.

**Comment by hqfking** [comment]
Hi @mezpahlan, @ShurikuS57 
In my case, I have to upload an iOS app which is around 500 MB to App center.  It kept getting the timeout error.  The current HockeyApp plugin works fine with this size of app.  Is there any future improvement about the timeout value?  It is currently blocking me from using plugin. 

Best regards.

**Comment by mezpahlan** [comment]
Hi @hqfking the old HockeyApp plugin had a timeout of 6000ms (6 seconds). In this PR we changed the connection and write timeouts to be 6 seconds for the AppCenter plugin. The only other thing we could do is the same for read timeouts, or bump the value again.

I'm sure you can understand my dilemma in that I can't keep bumping the timeout values indefinitely so it would help if you could isolate what precisely you feel the timeout value should be and I can assess that once you do.

Also:
1. Could you start a separate issue on Jenkins JIRA for this. You can find instructions in the README.
2. Any stacktraces would be nice.

**Pull request merged**
