### PR TITLE
[JENKINS-59792] Update ReadMe with current state of plugin

### PR DESCRIPTION
**Pull request by abelberhane**
Added to the documentation as changes have been made to the plugin. Added a breakdown of what the plugin expects in Jenkins and what features are currently available for the plugin.

### CODE REVIEW

**Comment by abelberhane** [comment]
I would also love to implement the ? bubble with additional information about each field for the plugin within Jenkins but have not done so yet. Any information pointing me in the right direction would be great. I would be happy to do some research and help flesh out the plugin when I can.

**Comment by mezpahlan** [comment]
Hi @abelberhane apologies for the slow reply. I've been away and am only just catching up on these PRs. I've not forgot about this and will find some time this week to look at this again.

**Comment by aberhaneTopps** [comment]
Hey @mezpahlan! No problem at all. I appreciate your help creating this and would like to help in any way that I can. I am researching some more things and am always open to discuss.

**Comment by mezpahlan** [comment]
Hi @abelberhane thanks for starting this. I agree that the README should be updated but I think some of these changes are better done elsewhere.

> 1) Removed the release notes from upcoming functionality since its been released

I think this is fine, we can take this one forward.

> 2) Added a breakdown of what the Plugin can currently do

I don't want to constantly remember to update the README when updating functionality. The changes are already in the change log and a "basic" upload is catered for in the README. That's as far as I want to go with it (specifically) in the README.

> 3) Added a breakdown of what the Plugin is expecting you to fill out and some helpful hints.

I think this is good but, again, better suited elsewhere. We already have [JENKINS-59377](https://issues.jenkins-ci.org/browse/JENKINS-59377) that looks to cater for this in the appropriate places.

I'll do a quick review now but I note that your branch needs updating against the current state of master.

**Comment by mezpahlan** [comment]
Closing in favour of #46

**Pull request closed without merging**
