### PR TITLE
[Jenkins 58311] not serializable exception when uploading apk

### PR DESCRIPTION
**Pull request by mezpahlan**
Turns out there were a few assumptions in the initial building of the plugin that assumed a single node..... oops!

We now execute tasks in a way that all parameters of the task can be serialised and thus transferred to a remote node before execution.

This does have one downside..... you must have the file to upload available on the node that you are attempting to run the upload. Sounds silly but if you build on one node, don't expect this plugin to upload from another node. So either find a way to transfer the file to the upload node, or build the file on the upload node.

### CODE REVIEW

**Comment by mezpahlan** [comment]
According to https://issues.jenkins-ci.org/browse/INFRA-2170 I need to close and reopen this because Jenkins CI machines have bugs in them...... ¯\\_(ツ)_/¯

**Comment by Sirrah** [comment]
I think I'm missing something in my internal model of how Jenkins executors work. Before sending in the bug report I tried I tried building/stashing the apk and unstashing/publishing in a separate stage.
For the bug report I put all build and publish steps in a single stage with an agent label.

Both options failed, but with this update the first approach (stash/unstash) should work?
That would be good enough for me, and probably my preferred approach.

I'd also be interested in learning how to properly constrain all steps of a stage to a single node.

I'll be able to test this on Monday. Thank you for picking this up!

**Comment by mezpahlan** [comment]
@Sirrah Me too! And full disclosure I don't normally do that in my pipelines. I target a node and run a build to create the artefact and perform the upload on the same node. In different stages, of course, but still on the same node.

However, what I struggled to understand is what as a plugin developer I need to do to support the case where an artefact is built on a different node to the one that is doing the uploading. Or even if that _should_ be a responsibility of the plugin or the author of the pipeline?

>Before sending in the bug report I tried I tried building/stashing the apk and unstashing/publishing in a separate stage. For the bug report I put all build and publish steps in a single stage with an agent label.

I can understand why this failed. Prior to these changes if you tried to assign this upload to a node other than master there happened to be objects in the graph of the upload task that were not serialisable. You can see that in your stack trace `java.io.NotSerializableException: retrofit2.Retrofit$1`. Jenkins at this point says, "Let me serialise your upload task and send it to another node for excution". It fails at this point if it can't serialise everything. Retrofit, by the way, is what we use as an HTTP client to do the actual uploading.

Regarding the quick script that you created that you mentioned in the bug report you can see the same problem `java.io.NotSerializableException: groovy.json.JsonSlurper`. However this time that's not coming from this plugin so I can't fix that. But it is, essentially, the same problem. Jenkins cannot send this bit of work to another node because it cannot fully serialise the object graph of this task.

>Both options failed, but with this update the first approach (stash/unstash) should work?

Actually, I _think_ both options will work now so pick your preferred one. But I haven't had time to test the unstashing version. I tested creating the app to upload *and* doing the upload on a node that was not master. But I suppose if you guarantee the upload artefact is available on whatever node you try and upload from then the plugin won't care as long as it can read it from the file system.

Good luck! Let me know how it goes.

**Comment by Sirrah** [comment]
Thanks for the additional explanation. I had assumed that the task failed to serialize the actual apk file and for both stacktraces it failed in a slightly different way.
Your explanation makes more sense within the concept of the Jenkins pipeline.

I'll let you know how it turns out!

**Comment by Sirrah** [comment]
@mezpahlan The first run resulted in a `500 - Internal error`:
```
[Pipeline] step
Creating an upload resource.
Upload resource successful.
Uploading app to resource.
Upload app successful.
Committing resource.
io.jenkins.plugins.appcenter.AppCenterException: java.util.concurrent.ExecutionException: retrofit2.HttpException: HTTP 500 Internal Server Error
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] bitbucketStatusNotify
Committing resource unsuccessful.
retrofit2.HttpException: HTTP 500 Internal Server Error
```
After that I went looking into which group the plugin distributes to.  The group is hardcoded to `Collaborators` which I hadn't used to distribute a build before. I then distributed an apk to this group manually through the AppCenter portal.
That worked and I ran the Jenkins build again, which now worked as well!
I'm not sure whether the 500 error is related to the above or was just a temporary glitch in AppCenter.

Do you have plans to add a 'Distribution group' parameter?

The upload is working now, I'm very glad with your help!

**Comment by mezpahlan** [comment]
Hi @Sirrah Thank you for testing this. My bad, yes you're right Collaborators is the hard coded distribution group based on my own distribution groups. I will update the plugin to allow you to specify this yourself in an updated version. Probably 0.2 of this plugin. 

For now I think this probably satisfies your original issue? I'll create a new release now.

**Comment by mezpahlan** [comment]
If anyone is interested in helping out I've raised a bug to add distribution group support: https://issues.jenkins-ci.org/browse/JENKINS-58391

**Comment by Sirrah** [comment]
Thanks, this definitely solves my original issues and allows us to proceed with AppCenter.

I'm not sure what was missing from my PR with the 'distribution group' parameter, but I'm looking forward to that 0.2 release :)

**Pull request merged**
