### PR TITLE
[JENKINS-59942] Add stats badges to README

### PR DESCRIPTION
**Pull request by mskadu**
Per JENKINS-59942

### CODE REVIEW

**Comment by mskadu** [comment]
Hi @mezpahlan - it's not apparent to me what caused the check to fail. Perhaps you could point me to it? Tx

**Comment by mezpahlan** [comment]
Seems like a genuine test failure. But not in anything that you have introduced. Some issue with Windows file paths and the test assuming Unix like file separators. Let me see if I can fix that and I'll update your branch if I can.

**Comment by mezpahlan** [comment]
Right, I think I've fixed that with #39 . I'll merge that into this and then give your PR a review.

**Comment by mezpahlan** [comment]
Yup looks great! Thank you @mskadu .

**Pull request merged**
